% Auto-generated by cameraCalibrator app on 14-Feb-2024
%-------------------------------------------------------


% Define images to process
imageFileNames = {'D:\DELL XPS Backup Bishal\Bishal\DELTA\Python S\CalibrationImages\img1.jpg',...
    'D:\DELL XPS Backup Bishal\Bishal\DELTA\Python S\CalibrationImages\img2.jpg',...
    'D:\DELL XPS Backup Bishal\Bishal\DELTA\Python S\CalibrationImages\img4.jpg',...
    'D:\DELL XPS Backup Bishal\Bishal\DELTA\Python S\CalibrationImages\img5.jpg',...
    'D:\DELL XPS Backup Bishal\Bishal\DELTA\Python S\CalibrationImages\img6.jpg',...
    'D:\DELL XPS Backup Bishal\Bishal\DELTA\Python S\CalibrationImages\img7.jpg',...
    'D:\DELL XPS Backup Bishal\Bishal\DELTA\Python S\CalibrationImages\img8.jpg',...
    'D:\DELL XPS Backup Bishal\Bishal\DELTA\Python S\CalibrationImages\img9.jpg',...
    'D:\DELL XPS Backup Bishal\Bishal\DELTA\Python S\CalibrationImages\img10.jpg',...
    'D:\DELL XPS Backup Bishal\Bishal\DELTA\Python S\CalibrationImages\img11.jpg',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 29;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
